[package]
name = "rand_example"
version = "0.1.0"
edition = "2021"

[dependencies]
opencv = "0.93.1"
rand = "0.8.5"
regex = "1.11.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
